### ISSUE TITLE
Import di Bootstrap

### ISSUE THREAD

**Issue by cerv4ntes** [overclokk/italystrap#10]
Ciao Enea,
ho visto che sei passato a SASS definitivamente e dai file leggo:

`/// Importo tutti i file Bootstrap così posso ottimizzare meglio i css
// @import "../bower/bootstrap-sass/assets/stylesheets/bootstrap";
// Core variables and mixins
@import "bootstrap/variables";
@import "bootstrap/mixins";
`
Mi chiedo però come faccia ad importarli, la cartella bower nel progetto non c'è e non riesco a trovare un riferimento. Mi farebbe piacere (come nella versione precedente del tema) poter tenere i file sotto mano, ovvero avere bootstrap fisicamente nel tema per fare eventuali modifiche.

Grazie in anticipo per la delucidazione

**Comment by overclokk** [comment]
Ciao @cerv4ntes,
sto finendo di scrivere la documentazione, se guardi nello starter child https://github.com/overclokk/ItalyStrap-child ho aggiunto il file bower.js (mi ero dimenticato di aggiungerlo prima), con bower puoi gestire le dipendenze dei file css e js https://bower.io/ basta che usi `bower install` e carica tutto, il file grunt nel child è già aggiornato con il path di default di bower.
Se hai altre domande chiedi pure.

**Comment by cerv4ntes** [comment]
Wow! che velocità!
Non uso bower al momento. Come posso risolvere in pratica lavoro con il Sublime Text - MAMP e Koala in ascolto sui file SASS e LESS come posso risolvere la questione?

Grazie ancora!

**Comment by overclokk** [comment]
Allora in quel caso puoi copiare nel tuo child la cartella di bower che è inclusa nel tema genitore.

Domanda, stai usando la versione nel branch Dev?

**Comment by cerv4ntes** [comment]
Perdonami la domanda sciocca ma dov'è questa cartella che io non la vedo nel repository

**Comment by overclokk** [comment]
Hai ragione, le cartelle con le dipendenze non sono presenti perché quelle vanno generate localmente, è giusto che ognuno usi l'ambiente di sviluppo che preferisce, c'è anche chi non vuole usare bootstrap, se non usi bower allora devi aggiornare il path di dove hai i file less o sass di bootstrap (che ovviamente ti dovrai scaricare tu con il metodo che preferisci e metterle nella cartella a te più comoda) quindi con il tuo compiler fai il resto.
