### ISSUE TITLE
Versione BETA: errore make()

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/italystrap#11]
Ciao Enea.

Sto testando la nuova versione del tema (BETA), scaricato dal sito del progetto.
Lo sto testanto su un sito su altervista. Dopo aver caricato il tema genitore e figlio, al caricamento della pagina mi compare questo errore. 

Fatal error: Call to a member function make() on a non-object in /membri/agconsulting/is_2/wp/wp-content/themes/italystrap/lib/_init.php on line 21

**Comment by overclokk** [comment]
Ciao @AndrGelmini assicurati che il plugin sia attivo, eventualmente riscarica il tema che ho applicato diversi fix.

**Comment by AndrGelmini** [comment]
Ciao Enea. 

Avevi ragione, devo aver dimenticato un passaggio nella procedura di test.. e mi sono dimentivato di installare il plugin. 
Ora ho risolto, l'errore precedente non lo emana più, ora però se punto vero la home mi viene fuori questo errore: 

Fatal error: Cannot declare class ItalyStrap\Core\Templates\Nav_Menu because the name is already in use in /membri/agconsulting/is_2/wp/wp-content/themes/italystrap/core/Templates/Nav_Menu.php on line 26

Scusa la domanda.. quale versione del tema devo scaricare?  perché io sto testando questo tema padre:

https://github.com/overclokk/ItalyStrap/releases/download/4.0.0-beta.2/ItalyStrap.4.0.0-beta.2.zip
e questo tema figlio

https://github.com/overclokk/ItalyStrap-child/releases/download/2.0.0/italystrap-child.2.0.0.zip

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
quelli sono errori già fixati ma sono nella Dev, ovviamente creare una release per ogni fix effettuato diventerebbe ingestibile quindi ne creo una ogni tanto quando reputo sia il caso di farlo.
Se in locale usi git puoi semplicemente usare il comando git pull per tirare giù tutti gli ultimi fix e tenerti sempre in pari.
Ovviamente essendo ancora in beta possono capitare questi errori, è normale, quando sarà disponibile la versione stabile le cose cambieranno.
