### ISSUE TITLE
Problema installazione

### ISSUE THREAD

**Issue by FrankDuma** [overclokk/italystrap#14]
Ho intallato il plugin ACM e ho installato il tema con il plugin GitHub Updater

ma quando attivo il tema mi viene questo avviso:

> Warning: require(/home/dumaweb0/public_html/wp-content/themes/italystrap/vendor/autoload.php): failed to open stream: No such file or directory in /home/dumaweb0/public_html/wp-content/themes/italystrap/lib/bootstrap.php on line 36
> 
> Fatal error: require(): Failed opening required '/home/dumaweb0/public_html/wp-content/themes/italystrap/vendor/autoload.php' (include_path='.:/usr/local/php70/pear') in /home/dumaweb0/public_html/wp-content/themes/italystrap/lib/bootstrap.php on line 36

Quale può essere il problema?
sbaglio qualcosa o è un bug?

**Comment by overclokk** [comment]
Ciao @FrankDuma ,
se scarichi la repo del tema con `git clone` allora devi anche dare il comando `composer update --no-dev` per creare la cartella vendor, questo ti permette di avere le dipendenze sempre aggiornate, altrimenti direttamente dalla pagina delle release scarichi lo zip in cui è contenuto tutto https://github.com/overclokk/italystrap/releases

Ovviamente mi ero dimenticato di scriverlo nel readme :-)

**Comment by FrankDuma** [comment]
Grazie per la veloce risposta, ho risolto
ora però sorge un altro problema
se installo il tema child non prende i css del tema parent, il sito è completamente privodi css
ho saltato qualche altro passaggio??

**Comment by overclokk** [comment]
Lo scopo del child è quello di creare la parte grafica del sito quindi è giusto che non venga caricato il css del tema genitore, puoi inserire tu il css nella cartella css del tema child, idem per i js.

Di default il nome del css o js che viene utilizzato è `custom`, quindi `custom.css e custom.js` se hai bisogno di css o js specifici per pagina puoi chiamarli con il nome del file template su cui dovrà essere caricato, per esempio, `home.php > home.css > home.js`.

Questo ti permette anche di poter caricare vanilla css|js.

**Comment by FrankDuma** [comment]
Ottimo
grazie ancora

**Comment by overclokk** [comment]
Se hai ancora bisogno chiedi pure.
