### ISSUE TITLE
Utilizzo Tema Child

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/ItalyStrap#4]
Salve.
Grazie per aver creato questo fantastico tema starter, oggi mi sto mettendo all'opera per modificare la struttura griglia e alcune parti di css. Ma non riesco proprio a far sovrascrivere le direttive css del tema child a quelle del tema padre.. 

Mi sai indicare la procedura giusta?

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
grazie a te per utilizzare ItalyStrtap, hai scaricato il tema child da qui https://github.com/overclokk/ItalyStrap-child ?

**Comment by AndrGelmini** [comment]
Ciao @overclokk  
Ho seguito la "guida" su italystrap.it..

Puoi vedere tu stesso il qui www.agconsulting.altervista.org il sito è un sito di test dove faccio varie prove su wp e temi, lo utilizzo sopratutto perché i soci posso vedere che cosa combino e posso visionare e consigliare. 

Sembra quasi che non venga caricato proprio lo stile del figlio. io al momento nel tema chiamato ItalyStrap-child ho inserito due righe di codice in style.css 

    body{ background-color: #f5f5f5 !important;}
    header{ background: #212a34;}

Come potrai notare dal template sto cercando di creare uno stile a tutto schermo.
Ti segnalo anche una piccola cosa che ho notato. Se utilizzo il tema Italistrap "padre" mi si attiva il pannello di controllo tema, se invece come nel mio caso utilizzo il tema figlio questo pannello non si visualizza.

**Comment by overclokk** [comment]
@AndrGelmini il file style.css non è utilizzato per inserire il proprio stile, come puoi vedere dal file che gestisce gli script https://github.com/overclokk/ItalyStrap-child/blob/master/lib/script.php style.css non viene caricato, questo file è solo utilizzato per essere visto da WordPress quando attivi il tema.

Per inserire i tuoi stili puoi usare:
home.css
singular.css
archive.css
(custom.css solo nel caso gli altri non vengano caricati, ma sono casi particolari, diciamo che si può considerare una fallback)

admin.css invece serve per caricare lo stile da visualizzare nell'editor

Questa struttura serve per caricare lo stile solo dove effettivamente necessario.

Per sviluppare ti consiglio l'utilizzo di grunt http://gruntjs.com/ e nel tema già trovi i file base da cui partire con i moduli da usare, per esempio se hai visto c'è una cartella di nome sass e less all'interno di css/src, in less sono contenuti i file less di Bootstrap e in sass sono contenuti i file che utilizzo per tutto il lavoro di ottimizzazione css, provalo.

Se non vuoi usare quegli strumenti allora usa solo i file che ti ho indicato prima ma ricordati che sarebbe utile minificassi il codice sempre in ottica di ottimizzazione delle performance.

**Comment by AndrGelmini** [comment]
Ottimo grazie mille.. 

Grunt ho appena capito a che cosa serve :-D ci dovrò mettere le mani sicuramente!!! non appena riuscirò  a terminare i mille mila progetti che sto portando avanti contemporaneamente. 

Non sono molto ferrato di sass e less ma vorrei creare un tema in linea con le tue specifiche e tecniche cosi potrò essere aggiornato e sempre performante... che è quello che voglio dal e per il sito. 
Quindi mi informo e studio qualche cosina. alla fine della fiera oltre a due/tre div da aggiungere e 1 da togliere non dovo fare.. è più un cambio di colori dello sfondo. 

Grazie mille per le pronte risposte

**Comment by overclokk** [comment]
Di nulla, grazie a te per le domande :-)
Chiudo come risolto

**Comment by AndrGelmini** [comment]
Si si Chiudi pure.  non ho ancora provato a fare alcuna modifica css ma sicuramente appena riesco provo a fare qualche cosa cosina. Al massimo mi faccio vivo io su g+

**Comment by overclokk** [comment]
Puoi sempre aprire una issue nuova se ovviamente l'argomento è diverso.

Ciao
