### ISSUE TITLE
Mancato Aggiornamento di GitHub Updater

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/italystrap#6]
Salve.

Torno a chiedere info e oggi chiedo informazioni su GitHub Updater perché ho notato che la versione che fai installare quando si attiva lo stile, non si aggiorna, a me da un problema di connessione alla sorgente, anche se mi da la notifica di aggiornamento, al che mi sono adoperato per scaricare l'aggiornamento del plugin https://github.com/codepress/github-plugin-updater e tutto bene tranne che non ho idea di come poter settare il pannello delle impostazioni per far in modo che il tema si aggiorni. 

Grazie per la gentile attenzione.

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
vedro di capire il motivo del problema.

Ad ogni modo attivato il plugin non devi fare nulla, quando ci sarà un aggiornamento verrà segnalato dai classici aggiornamenti di WordPress.

**Comment by AndrGelmini** [comment]
.... a dire il vero di devo confessare che non è così, mmm sto segnalando questo "bug" procedurale perché il plugin: 

GitHub Updater mi segna un update di circa 3 versioni che non si aggiorna. 

ho personalmente effettuato l'update del tema bene due o tre volte su un paio di siti da me gestiti.  ormai lo uso come tema master di defoult per tutti i progetti lo trovo molto comodo e completo.  l'unica cosa che manca è un bel pannello nel child per gestire le immagini e le icone, ma  nulla che non si possa bypassare con ACF e option page

**Comment by overclokk** [comment]
Me lo sono segnato fra le cose da controllare.
