### ISSUE TITLE
Info su funzione descrizione opengraf

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/italystrap#7]
salve.  sto sbattendo la resta sulla twitter cards 

dal file: themes/ItalyStrap-child/lib/twitter_card.php

vedo che la descrizione è gestita dalla funzione italystrap_open_graph_desc() purtroppo quando vado a controllare il sorgente della pagina mi compare cosi: 

```
<meta name="twitter:description" value="" />
```

Sperando di aver fatto cosa gradita.

**Comment by overclokk** [comment]
Ciao @AndrGelmini grazie per la segnalazione, appena possibile vedo cosa sia successo.

**Comment by AndrGelmini** [comment]
felice di essere stato d'aiuto.
