### ISSUE TITLE
Potenziale Incompatibilità con Plug In -  Caldera Forum

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/italystrap#8]
Salve. 

Sto testando questo PlugIn con questo fantastico tema..  solo che sto riscontrando dei problemi di compatibilità sopratutto a causa, credo delle librerie Jquery. 

Chiedo se è possibile capire come poter aggirare questo problema...

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
non conosco quel plugin, qual'è il problema che riscontri?
Come utilizzi il tema?

**Comment by AndrGelmini** [comment]
Ciao @overclokk 

Il problema che riscontro è questo...  
Il plug-in funziona molto bene, con le funzionalità base.  mentre quando provo ad utilizzare alcuni field "speciali" questi non funzionano a causa di una incompatibilità jquery 

Uncaught ReferenceError: jQuery is not defined
agconsulting.altervista.org/:198 Uncaught ReferenceError: jQuery is not defined
agconsulting.altervista.org/:237 Uncaught ReferenceError: jQuery is not defined
agconsulting.altervista.org/:301 Uncaught ReferenceError: jQuery is not defined
agconsulting.altervista.org/:346 Uncaught ReferenceError: jQuery is not defined
parsley.min.js?ver=1.3.2.1:1 Accessing the method `addCatalog` through ParsleyValidator is deprecated. Simply call `window.Parsley.addCatalog(...)`

puoi vedere un esempio di una pagina qui.. ho inserito i field che a un primo esame non funzionano.... 

http://agconsulting.altervista.org/test-nl-aef/lp/test-form/

**Comment by overclokk** [comment]
Il problema è del plugin che non inserisce correttamente gli script js nel footer e invece li inserisce inline prima che venga caricato jQuery, potresti risolvere facendo caricare jQuery in header ma questo è molto brutto come metodo.
Altrimenti se non vuoi cambiare plugin dovresti contattare lo sviluppatore e segnalargli il problema.

**Comment by AndrGelmini** [comment]
Grazie @overclokk puntuale e preciso come al solito. 

Per il plugin, riporto una frase che ho letto su un sito.. Tutti plugin sono importanti ma tutti i plug-in sono sostituibili.. o una cosa del genere.. .

Contatto il programmatore per chiedere se esiste una soluzione, altrimenti provvederò a cambiare plug-in  o programmare io tutti i form.. anche la cosa non mi alletta.. ahaha

**Comment by overclokk** [comment]
Io per i form uso questo https://github.com/WebDevStudios/CMB2

**Comment by AndrGelmini** [comment]
Lo conosco molto bene.. ma il form più piccolo che devo fare ha più di 40 field.. mi risulta lungo e complicato con CMB2 anche se come libreria e fantastica.. Ho visto che vuoi implementarla nel tema, fantastica idea direi.
