### ISSUE TITLE
Potenziale Bug con glyphicons in custom menu

### ISSUE THREAD

**Issue by AndrGelmini** [overclokk/ItalyStrap#9]
Ciao. 

Segnalo questo potenziale bug.. nel senso che ho provato in ogni modo a far funzionare questa impostazione ma credo o che c'è un bug o mi sono perso qualche pezzo da qulche parte. 

Procedimento seguito. 

Vado nella sezione menu,
Imposto una icona a caso: <span class="social social-xing"></span> 
Salvo il menù.. 
Carico la home del sito e l'icona non c'è,
Vado nella sezione admin del menu e nel campo glyphicons non compare nulla.. 

Dove Sbaglio? 

Ho provato a dare un'occhio a questo: http://www.wpexplorer.com/adding-custom-attributes-to-wordpress-menus/ riportanto nel file ItalyStrap_custom_menu.php ma non trovo nulla che non va. 

EDIT: cercando una soluzione valida per questa situazione... ho trovato questa libreria.. https://github.com/kucrut/wp-menu-item-custom-fields ..

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
come inserisci il nome dell'icona?
Che versione del tema hai?
Hai provato a disattivare il tema e riattivarlo?
Provato a disattivare i plugin?
In questa demo dove ho ancora la 3.0.5 funziona correttamente http://demo.italystrap.it/

**Comment by AndrGelmini** [comment]
Versione child installata 3.0.5 

Inserisco la classe dell'icona.. tipo <i class="**glyphicon glyphicon-unchecked** "></i>

Non ho disattivato o reinstallato nulla perchè non ha mai funzionato, almeno nel mio caso, come funzionalità. 

ho risolto inserendo nel file function.php questo:
`/////////////////////////////////////////////////

add_action('wp_update_nav_menu_item', 'italystrap_update_custom_nav_fields',10, 3);
function italystrap_update_custom_nav_fields($menu_id, $menu_item_db_id, $args ) {
    if ( is_array($_REQUEST['menu-item-glyphicon']) ) {
        $custom_value = $_REQUEST['menu-item-glyphicon'][$menu_item_db_id];
        update_post_meta( $menu_item_db_id, '_menu_item_glyphicon', $custom_value );
    }
}

/*
 * Adds value of new field to $item object that will be passed to     Walker_Nav_Menu_Edit_Custom
 */
add_filter( 'wp_setup_nav_menu_item','italystrap_add_custom_nav_fields' );
function italystrap_add_custom_nav_fields($menu_item) {
    $menu_item->glyphicon = get_post_meta( $menu_item->ID, '_menu_item_glyphicon', true );
    return $menu_item;
}

add_filter( 'wp_edit_nav_menu_walker', 'italystrap_edit_walker',10,2 );
function italystrap_edit_walker($walker,$menu_id) {
    return 'Admin_Edit_Custom_Walker_Nav_Menu_Edit_Custom';
}`

**Comment by overclokk** [comment]
Ottimo, allora segno come risolto.
